version: '3'

volumes:
  database_local:

services:
  vehicelbrand_local:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: vehicelbrand_local
    container_name: vehicelbrand_local
    working_dir: /app
    volumes:
      - database_local:/app/database
      - .:/app
    ports:
      - "8000:8000"
    command: /start.sh
