# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-26 07:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleBrandInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_plate', models.CharField(max_length=20)),
                ('driver_name', models.CharField(max_length=20)),
                ('start_place', models.CharField(max_length=30)),
                ('end_place', models.CharField(max_length=30)),
                ('sign_serial_number', models.CharField(max_length=20)),
                ('transport_company', models.CharField(max_length=40)),
                ('business_issuer', models.CharField(max_length=20)),
                ('main_apporach', models.CharField(max_length=40)),
                ('effective_date', models.CharField(max_length=40)),
            ],
        ),
    ]
